version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: juanitamamani_CamposBaseDatos_1
  nodeweb:
    environment: 
      BASE_IP: "mongodb"
    build: .
    image: node-imagen
    container_name: Juanitamamani_JuanitaWeb_1
    depends_on: 
      - mongodb
    ports: 
      - 3000:3000
