version: "3"

services:
 mysqldb:
  image: mysql:5.7
  container_name: db3
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=123456
  webphp:
    image:prueba-php
  ports:
   - 8080:80
  environment:
   - MYSQL_ROOT_PASSWORD=mysqldb
