version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: base_datos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "crud-php"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - dbphp-docker:/var/lib/mysql

  projeto:
    links:
      - "db"
    container_name: php-crud
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    restart: always
volumes:
  dbphp-docker:
